/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comedorUPC;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author keiinerp
 */
public class Diseño extends javax.swing.JFrame {

    /**
     * Creates new form Diseño
     */
    public Diseño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoEmpleadosCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        contratistaCombo = new javax.swing.JComboBox<>();
        nombreTexto = new javax.swing.JTextField();
        identificacionTexto = new javax.swing.JTextField();
        guardarBoton = new javax.swing.JButton();
        cerrarBoton = new javax.swing.JButton();
        empleadosConPrimaBoton = new javax.swing.JButton();
        empleadosSinPrimaBoton = new javax.swing.JButton();
        totalAsignadoBoton = new javax.swing.JButton();
        conMayorBoton = new javax.swing.JButton();
        conMenorBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prima empleados");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Identificación:");

        jLabel4.setText("Tipo de Empleado");

        tipoEmpleadosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DOCENTE", "ADMINISTRATIVO", "CONTRATISTA", "OTRO" }));

        jLabel5.setText("Contratistas:");

        nombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextoActionPerformed(evt);
            }
        });

        identificacionTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionTextoActionPerformed(evt);
            }
        });

        guardarBoton.setText("Guardar");
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        cerrarBoton.setText("Cerrar");
        cerrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBotonActionPerformed(evt);
            }
        });

        empleadosConPrimaBoton.setText("Empleados con prima");
        empleadosConPrimaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosConPrimaBotonActionPerformed(evt);
            }
        });

        empleadosSinPrimaBoton.setText("Empleados sin prima");
        empleadosSinPrimaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosSinPrimaBotonActionPerformed(evt);
            }
        });

        totalAsignadoBoton.setText("Total asignado en primas");
        totalAsignadoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAsignadoBotonActionPerformed(evt);
            }
        });

        conMayorBoton.setText("Con mayor prima");
        conMayorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conMayorBotonActionPerformed(evt);
            }
        });

        conMenorBoton.setText("Con menor prima");
        conMenorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conMenorBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identificacionTexto)
                            .addComponent(nombreTexto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoEmpleadosCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(123, 123, 123)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(contratistaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(empleadosSinPrimaBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empleadosConPrimaBoton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalAsignadoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conMayorBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(conMenorBoton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(identificacionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoEmpleadosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contratistaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadosConPrimaBoton)
                    .addComponent(totalAsignadoBoton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadosSinPrimaBoton)
                    .addComponent(conMayorBoton)
                    .addComponent(conMenorBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBoton)
                    .addComponent(cerrarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextoActionPerformed

    private void identificacionTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionTextoActionPerformed

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
nombre=nombreTexto.getText();
identidad=identificacionTexto.getText();
tipoEmpleado=(String) tipoEmpleadosCombo.getSelectedItem();
asignarSueldo(tipoEmpleado);
saberSiTendraPrima(tipoEmpleado);
if(saberSiTendraPrima(tipoEmpleado)==true){
calcularPrima(tipoEmpleado, sueldo);
listaEmpleados.add(new Empleado(nombre,identidad,sueldo,prima,tipoEmpleado));
conMayorPrima();
conMenorPrima();
totalAsignadoEnPrimas();
if(tipoEmpleado.equals("CONTRATISTA")){
    contratistaCombo.addItem(identidad+" "+nombre+" "+tipoEmpleado+" "+sueldo+" "+prima);
}   
}
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void empleadosConPrimaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosConPrimaBotonActionPerformed
JOptionPane.showMessageDialog(null, "La cantidad de los empleados con primas es:    "+conPrima);
    }//GEN-LAST:event_empleadosConPrimaBotonActionPerformed

    private void empleadosSinPrimaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosSinPrimaBotonActionPerformed
JOptionPane.showMessageDialog(null,"La cantidad de los empleados sin primas es: "+sinPrima);
    }//GEN-LAST:event_empleadosSinPrimaBotonActionPerformed

    private void totalAsignadoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAsignadoBotonActionPerformed
JOptionPane.showMessageDialog(null, "El total asignado en primas es de: "+totAsignado);
    }//GEN-LAST:event_totalAsignadoBotonActionPerformed

    private void conMayorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conMayorBotonActionPerformed
JOptionPane.showMessageDialog(null, "El empleado con mayor prima es:    "+conMayorPrima().getNombre());
    }//GEN-LAST:event_conMayorBotonActionPerformed

    private void conMenorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conMenorBotonActionPerformed
JOptionPane.showMessageDialog(null, "El empleado con menor prima es:    "+conMenorPrima());
    }//GEN-LAST:event_conMenorBotonActionPerformed

    private void cerrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBotonActionPerformed
System.exit(0);
    }//GEN-LAST:event_cerrarBotonActionPerformed

    public void totalAsignadoEnPrimas(){
        for (int i = 0; i < listaEmpleados.size(); i++) {
            totAsignado=totAsignado+listaEmpleados.get(i).getPrima();
        }
    }
    public Empleado conMayorPrima(){
        for (int i = 0; i < listaEmpleados.size(); i++) {
            if(mayor<listaEmpleados.get(i).getPrima()){
                mayor=listaEmpleados.get(i).getPrima();
                conMayor=listaEmpleados.get(i);
        }
    }     
        return conMayor;
    }
    public String conMenorPrima(){
     String nombree=null;    
     for (int i = 0; i < listaEmpleados.size(); i++) {
            if(listaEmpleados.get(i).getPrima()<=menor){
                menor=listaEmpleados.get(i).getPrima();
                nombree=listaEmpleados.get(i).getNombre();
        }
    }       
    return nombree;
        }
    public boolean saberSiTendraPrima(String tipoEmpleado){
    boolean saberSiTendraPrima;
        if(tipoEmpleado.equals("OTRO")){
    sinPrima++;
    JOptionPane.showMessageDialog(null,"Este empleado no tiene derecho a prima");
    saberSiTendraPrima=false;
}
else{
    conPrima++;
    saberSiTendraPrima=true;
}
        return saberSiTendraPrima;
    }
    public void asignarSueldo(String tipoEmpleado){
    if(tipoEmpleado.equals("DOCENTE")){
        sueldo=3700000;
    }
    if(tipoEmpleado.equals("ADMINISTRATIVO")){
        sueldo=4000000;
    }
    if("CONTRATISTA".equals(tipoEmpleado)){
        sueldo=3500000;
    }
}
    public void calcularPrima(String tipoEmpleado, int sueldo){
    if("DOCENTE".equals(tipoEmpleado)){
        prima=(int) (sueldo*0.35);
    }
    if("CONTRATISTA".equals(tipoEmpleado)){
        prima=(int)(sueldo*0.12);
    }
    if("ADMINISTRATIVO".equals(tipoEmpleado)){
        prima=(int)(sueldo*24);
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarBoton;
    private javax.swing.JButton conMayorBoton;
    private javax.swing.JButton conMenorBoton;
    private javax.swing.JComboBox<String> contratistaCombo;
    private javax.swing.JButton empleadosConPrimaBoton;
    private javax.swing.JButton empleadosSinPrimaBoton;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField identificacionTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JComboBox<String> tipoEmpleadosCombo;
    private javax.swing.JButton totalAsignadoBoton;
    // End of variables declaration//GEN-END:variables
    ArrayList<Empleado> listaEmpleados = new ArrayList<>();                        
public String nombre;
public String identidad;
public String tipoEmpleado;
public int sueldo;
public int prima;
public int sinPrima=0;
public int conPrima=0;
public int mayor=0;
public int menor=9999999;
public Empleado conMayor=null;
public Empleado conMenor=null;
public int totAsignado;
}
